name: mech_qt
channels:
  - conda-forge
  - bioconda
dependencies:
  - aom=3.9.1=h7bae524_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he0f2337_1
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=h3ff7a7c_1
  - fluidsynth=2.5.2=h2ab8666_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=hce30654_0
  - graphite2=1.3.14=hec049ff_2
  - harfbuzz=12.3.2=h3103d1b_0
  - icu=78.2=h38cb7af_0
  - lame=3.100=h1a8c8d9_1003
  - lerc=4.0.0=hd64df32_1
  - libavif16=1.3.0=hde9513d_3
  - libcxx=21.1.8=h55c6f16_2
  - libdeflate=1.25=hc11a715_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=hcf2aa1b_0
  - libflac=1.5.0=h6824b09_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libglib=2.86.3=he378b5c_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblzma=5.8.2=h8088a28_0
  - libmad=0.15.1b=h1a8c8d9_1001
  - libogg=1.3.5=h48c0fde_1
  - libopus=1.6.1=h1a92334_0
  - libpng=1.6.55=h132b30e_0
  - libsndfile=1.2.2=hf95f74e_2
  - libsqlite=3.51.2=h1ae2325_0
  - libtiff=4.7.1=h4030677_1
  - libusb=1.0.29=hbc156a2_0
  - libvorbis=1.3.7=h81086ad_2
  - libvulkan-loader=1.4.341.0=h3feff0a_0
  - libwebp-base=1.6.0=h07db88b_0
  - libzlib=1.3.1=h8359307_2
  - mpg123=1.32.9=hf642e45_0
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.1=hd24854e_1
  - opusfile=0.12=h5643135_2
  - packaging=26.0=pyhcf101f3_0
  - pcre2=10.47=h30297fc_0
  - pip=26.0=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - portaudio=19.7.0=h5833ebf_0
  - portmidi=2.0.8=haf25636_0
  - pygame=2.6.1=py311hc3e7c57_0
  - pyserial=3.5=pyhcf101f3_2
  - python=3.11.14=h18782d2_3_cpython
  - python_abi=3.11=6_cp311
  - rav1e=0.7.1=h0716509_3
  - readline=8.3=h46df422_0
  - sdl2=2.32.56=h248ca61_0
  - sdl2_image=2.8.2=h376e2e1_1
  - sdl2_mixer=2.6.3=h45fadf6_2
  - sdl2_ttf=2.24.0=h443c5de_0
  - sdl3=3.4.0=h6fa9c73_0
  - setuptools=80.10.2=pyh332efcf_0
  - svt-av1=4.0.0=h0cb729a_0
  - tk=8.6.13=h010d191_3
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - colorama==0.4.6
      - markdown==3.10.1
      - numpy==1.26.4
      - pillow==12.1.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.18.0
      - pyqtgraph==0.14.0
      - qtpy==2.4.3
      - qtwidgets==1.1
prefix: /opt/homebrew/Caskroom/mambaforge/base/envs/mech_qt
