name: mech_qt
channels:
  - conda-forge
  - bioconda
dependencies:
  - aom=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - dav1d=1.2.1
  - dbus=1.16.2
  - fluidsynth=2.5.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - graphite2=1.3.14
  - harfbuzz=12.3.2
  - icu=78.2
  - lame=3.100
  - lerc=4.0.0
  - libavif16=1.3.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libglib=2.86.3
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblzma=5.8.2
  - libmad=0.15.1b
  - libogg=1.3.5
  - libopus=1.6.1
  - libpng=1.6.55
  - libsndfile=1.2.2
  - libsqlite=3.51.2
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.341.0
  - libwebp-base=1.6.0
  - libzlib=1.3.1
  - mpg123=1.32.9
  - ncurses=6.5
  - openssl=3.6.1
  - opusfile=0.12
  - packaging=26.0
  - pcre2=10.47
  - pip=26.0
  - pixman=0.46.4
  - portaudio=19.7.0
  - portmidi=2.0.8
  - pygame=2.6.1
  - pyserial=3.5
  - python=3.11.14
  - python_abi=3.11
  - rav1e=0.7.1
  - readline=8.3
  - sdl2=2.32.56
  - sdl2_image=2.8.2
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.24.0
  - sdl3=3.4.0
  - setuptools=80.10.2
  - svt-av1=4.0.0
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.46.3
  - zstd=1.5.7
  - pip:
      - colorama==0.4.6
      - markdown==3.10.1
      - numpy==1.26.4
      - pillow==12.1.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.18.0
      - pyqtgraph==0.14.0
      - qtpy==2.4.3
      - qtwidgets==1.1
prefix: /opt/homebrew/Caskroom/mambaforge/base/envs/mech_qt
